/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsToolIdRouteImport } from './routes/tools.$toolId'
import { Route as DashboardReceivedRentalsRouteImport } from './routes/dashboard.received-rentals'
import { Route as DashboardMyToolsRouteImport } from './routes/dashboard.my-tools'
import { Route as DashboardMyRentalsRouteImport } from './routes/dashboard.my-rentals'
import { Route as ToolsToolIdRentRouteImport } from './routes/tools.$toolId.rent'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsToolIdRoute = ToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReceivedRentalsRoute =
  DashboardReceivedRentalsRouteImport.update({
    id: '/received-rentals',
    path: '/received-rentals',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardMyToolsRoute = DashboardMyToolsRouteImport.update({
  id: '/my-tools',
  path: '/my-tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyRentalsRoute = DashboardMyRentalsRouteImport.update({
  id: '/my-rentals',
  path: '/my-rentals',
  getParentRoute: () => DashboardRoute,
} as any)
const ToolsToolIdRentRoute = ToolsToolIdRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => ToolsToolIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/my-rentals': typeof DashboardMyRentalsRoute
  '/dashboard/my-tools': typeof DashboardMyToolsRoute
  '/dashboard/received-rentals': typeof DashboardReceivedRentalsRoute
  '/tools/$toolId': typeof ToolsToolIdRouteWithChildren
  '/tools/$toolId/rent': typeof ToolsToolIdRentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/my-rentals': typeof DashboardMyRentalsRoute
  '/dashboard/my-tools': typeof DashboardMyToolsRoute
  '/dashboard/received-rentals': typeof DashboardReceivedRentalsRoute
  '/tools/$toolId': typeof ToolsToolIdRouteWithChildren
  '/tools/$toolId/rent': typeof ToolsToolIdRentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/my-rentals': typeof DashboardMyRentalsRoute
  '/dashboard/my-tools': typeof DashboardMyToolsRoute
  '/dashboard/received-rentals': typeof DashboardReceivedRentalsRoute
  '/tools/$toolId': typeof ToolsToolIdRouteWithChildren
  '/tools/$toolId/rent': typeof ToolsToolIdRentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/my-rentals'
    | '/dashboard/my-tools'
    | '/dashboard/received-rentals'
    | '/tools/$toolId'
    | '/tools/$toolId/rent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/my-rentals'
    | '/dashboard/my-tools'
    | '/dashboard/received-rentals'
    | '/tools/$toolId'
    | '/tools/$toolId/rent'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/my-rentals'
    | '/dashboard/my-tools'
    | '/dashboard/received-rentals'
    | '/tools/$toolId'
    | '/tools/$toolId/rent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ToolsToolIdRoute: typeof ToolsToolIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$toolId': {
      id: '/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof ToolsToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/received-rentals': {
      id: '/dashboard/received-rentals'
      path: '/received-rentals'
      fullPath: '/dashboard/received-rentals'
      preLoaderRoute: typeof DashboardReceivedRentalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-tools': {
      id: '/dashboard/my-tools'
      path: '/my-tools'
      fullPath: '/dashboard/my-tools'
      preLoaderRoute: typeof DashboardMyToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-rentals': {
      id: '/dashboard/my-rentals'
      path: '/my-rentals'
      fullPath: '/dashboard/my-rentals'
      preLoaderRoute: typeof DashboardMyRentalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/tools/$toolId/rent': {
      id: '/tools/$toolId/rent'
      path: '/rent'
      fullPath: '/tools/$toolId/rent'
      preLoaderRoute: typeof ToolsToolIdRentRouteImport
      parentRoute: typeof ToolsToolIdRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardMyRentalsRoute: typeof DashboardMyRentalsRoute
  DashboardMyToolsRoute: typeof DashboardMyToolsRoute
  DashboardReceivedRentalsRoute: typeof DashboardReceivedRentalsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMyRentalsRoute: DashboardMyRentalsRoute,
  DashboardMyToolsRoute: DashboardMyToolsRoute,
  DashboardReceivedRentalsRoute: DashboardReceivedRentalsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ToolsToolIdRouteChildren {
  ToolsToolIdRentRoute: typeof ToolsToolIdRentRoute
}

const ToolsToolIdRouteChildren: ToolsToolIdRouteChildren = {
  ToolsToolIdRentRoute: ToolsToolIdRentRoute,
}

const ToolsToolIdRouteWithChildren = ToolsToolIdRoute._addFileChildren(
  ToolsToolIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ToolsToolIdRoute: ToolsToolIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
